spring:
  application:
    name: audit-governance
server:
  port: 8086
logging:
  pattern:
    level: "%5p [trace_id=%X{trace_id:-}]"
management:
  endpoints:
    web:
      exposure:
        include: health
