package com.medassist.agent.llm;

public enum LlmFailureReason {
  UNAVAILABLE,
  TIMEOUT,
  PROVIDER_ERROR,
  RATE_LIMITED,
  BUDGET_EXCEEDED,
  ALL_PROVIDERS_UNAVAILABLE,
  INVALID_RESPONSE,
  EGRESS_BLOCKED
}
